apiVersion: v1
entries:
  redis:
  - annotations:
      category: Database
      images: |
        - name: kubectl
          image: docker.io/bitnami/kubectl:1.29.2-debian-12-r3
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r16
        - name: redis
          image: docker.io/bitnami/redis:7.2.4-debian-12-r9
        - name: redis-exporter
          image: docker.io/bitnami/redis-exporter:1.58.0-debian-12-r4
        - name: redis-sentinel
          image: docker.io/bitnami/redis-sentinel:7.2.4-debian-12-r7
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 7.2.4
    created: "2026-05-28T15:04:40.776898401-07:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: 0d3269c8a9a676622508cedda68a6595d15770bdda899931a7e37817adcb8daf
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - https://pharaofranz.github.io/canfar-deployments/charts/redis-18.19.4.tgz
    version: 18.19.4
  skaha:
  - apiVersion: v2
    appVersion: 1.1.7
    created: "2026-05-28T15:04:40.773498587-07:00"
    dependencies:
    - name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: ^18.19.0
    - name: utils
      repository: file://../utils
      version: ^0.1.0
    description: A Helm chart to install the Skaha web service of the CANFAR Science
      Platform
    digest: da2a5e3bc8f919f417fd0b91fcfe5a686322cabaed9164bd64b01ace7c60bc16
    icon: https://www.canfar.net/css/images/logo.png
    maintainers:
    - email: djenkins.cadc@gmail.com
      name: Dustin Jenkins
    - email: shiny.brar@nrc-cnrc.gc.ca
      name: Shiny Brar
    name: skaha
    type: application
    urls:
    - https://pharaofranz.github.io/canfar-deployments/skaha-1.3.3.tgz
    version: 1.3.3
  utils:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-28T15:04:40.777078651-07:00"
    description: A library Helm chart for common tasks
    digest: 922c85d7ba144487ae1386d7f5b79769fb7617878d874f0f5b14dae9a8d0a851
    maintainers:
    - email: shiny.brar@nrc-cnrc.gc.ca
      name: Shiny Brar
    - email: djenkins.cadc@gmail.com
      name: Dustin Jenkins
    name: utils
    type: library
    urls:
    - https://pharaofranz.github.io/canfar-deployments/charts/utils-0.1.1.tgz
    version: 0.1.1
generated: "2026-05-28T15:04:40.766658293-07:00"
